<html>
<head>
    <title><?=$this->Config->viewerTitle;?></title>
    <meta name="robots" content="noindex">

    <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAGNSURBVDjLpVM9SwNBEJ297J1FQBtzjQj2dgppYiP4A1KZRoiFrYWt9rHyH6QUPBDTCimtLNSAnSB26YKg4EdMdsd5611cjwsIWRhmZ3f2zZuPVcxMsyx9fPF0NRfS2vM7lx2WtcQiJHvDRvZMluXMGNHstJH7+Wj09jHkOy1+tc3VxeC+P6TXT1sYZX2hT7cvS6lepv3zHUp2T8vXNw81dXT2yGwEGeERSbSVCC5qysYa+3vm9sJGmLFojceXJ9uklCqUIAic5G3IytahAAhqqVSiwWDwx6nogW9XKhWphaGAvC50Oh1qtVr/7oAdCwBQwjB00mg0qFqtUr1ed3YURZM7X7TWTqM2Gm3CASRJEur1etTtdp1DnrafFtJGMbVNGSBas9l0DrAzR6x8DdwASUB0RqNNGS2/gH7EInvCwMhkZTnlnX0GsP09tJER0BgMoAEAa1rETDIQvBkjBZeHMIjjuNB5Ggg0/oZWPGrHGwd7Fp9F2CAlgHKqf0aYXb6Y2mzE8d/IfrXVrN/5G81p6oa2mIEUAAAAAElFTkSuQmCC"/>
</head>
<style type="text/css">
    <?php include(__DIR__ . '/viewer.css'); ?>
</style>

<body>


<div class="fileListWrapper">
    <?php include(__DIR__ . '/fileList.phtml'); ?>
</div>



<div style="padding-top:3em; padding-bottom:2em;">
    <a href="<?=$this->viewLatestRequestUrl();?>">
        <button class="viewLatestRequestButton">View latest request</button>
    </a>
</div>




<?php include(__DIR__ . '/records.phtml'); ?>




<div style="padding-top:3em; padding-bottom:1em;">
    <a href="<?=$this->viewLatestRequestUrl();?>">
        <button class="viewLatestRequestButton viewLatestRequestButtonBottom">View latest request</button>
    </a>
</div>




<?php
if ($this->Config->tailErrorLogLines > 0)
{
    echo "<h1>Nginx error log:</h1>";
    $errorLogContent = htmlentities(`/usr/bin/tail --lines=60 /var/log/nginx/error.log`);
    $errorLogContent = nl2br($errorLogContent);
    echo $errorLogContent;

}
?>



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>


<script>
    $(document).ready(function () {

        var now = moment();
        $('time.timeAgo').each(function(i, e) {
            var time = moment($(e).attr('datetime'));
            $(e).html(time.from(now));
            $(e).attr('title', time.format('D MMM YYYY h:mma'));
        });

        var now = moment();
        $('time.localTimestamp').each(function(i, e) {
            var time = moment($(e).attr('datetime'));
            $(e).html(time.format('D MMM YYYY h:mm:ssa'));
        });




    });
</script>

</body>
</html>